package constants;

public enum RegionEnum {
    Tyva("17"),
    Orenburg("56"),
    Belgorod("31"),
    Saratov("64"),
    Voronezh("36"),
    ChukotkaAutonomousDistrict("87"),
    Buryatia("03"),
    Tatarstan("16"),
    Ulyanovsk("73"),
    Tomsk("70"),
    Sverdlovsk("66"),
    Bashkortostan("02"),
    Komi("11"),
    Yakutia("14"),
    Sevastopol("92"),
    Ingushetia("06"),
    Chechensk("20"),
    Crimea("91"),
    Primorsk("25"),
    Khakassia("19"),
    Krasnoyarsk("24"),
    Adygea("01"),
    Stavropolsk("26"),
    Kaliningradsk("39"),
    MariEl("12"),
    Kabardino_Balkaria("07"),
    Karachay_Cherkessia("09"),
    Udmurtia("18"),
    Khabarovsk("27"),
    Novgorod("53"),
    Kostroma("44"),
    Kalmykia("08"),
    Rostov("61"),
    Vologda("35"),
    Astrakhan("30"),
    NorthOssetiaAlania("15"),
    Tula("71"),
    Kaluga("40"),
    Yaroslavl("76"),
    Chuvashia("21"),
    Chelyabinsk("74"),
    Vladimirsk("33"),
    Mordovia("13"),
    Omsk("55"),
    Tambov("68"),
    Penza("58"),
    NizhnyNovgorod("52"),
    Ryazan("62"),
    Bryansk("32"),
    Pskov("60"),
    Kemerovo("42"),
    Transbaikal("75"),
    Amurskaya("28"),
    Novosibirsk("54"),
    Irkutsk("38"),
    Kurgan("45"),
    Kamchatka("41"),
    Altai("04"),
    Magadan("49"),
    JewishAutonomousRegion("79"),
    Lipetsk("48"),
    Murmansk("51"),
    Dagestan("05"),
    Smolensk("67"),
    Permian("59"),
    Krasnodar("23"),
    StPetersburg("78"),
    MoscowRegion("50"),
    Arkhangelsk("29"),
    Nenets("83"),
    YamaloNenetsAutonomousDistrict("89"),
    Tyumen("72"),
    KhantyMansiAutonomousOkrugYugra("86"),
    Mosckoy("77"),
    Orlovskaya("57"),
    Kursk("46"),
    Samara("63"),
    Leningradskaya("47"),
    Ivanovskaya("37"),
    Sakhalin("65"),
    Altaic("22"),
    Tverskaya("69"),
    Karelia("10");

    public final String code;


    RegionEnum(String code) {
        this.code = code;
    }
}

